name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  dockerize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t pollquest-ui .

      - name: Tag Docker image
        run: docker tag pollquest-ui nagaprya/pollquest-ui:latest

      - name: Log in to Docker registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image to registry
        run: docker push nagaprya/pollquest-ui:latest
